apiVersion: v1
kind: Pod
metadata: 
  name: fortune-configmap-volume
spec:
  containers:
  - image: joont92/fortune:env
    name: html-generator
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true    
  volumes:
  - name: html
    emptyDir: {}
  - name: config
    configMap:
      name: fortune-config