apiVersion: v1
kind: Pod
metadata:
  name: fortune-args
spec:
  containers:
  - image: joont92/fortune:args  
    name: html-generator
    args: ["2"]
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  volumes:
  - name: html
    emptyDir: {}