apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubia-green
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
        version: v2
    spec:
      containers:
      - name: nodejs
        image: luksa/kubia:v2