apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
# selector: // 아래 pod template 에서 추출 가능
#   app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
          ports:
          - containerPort: 8080