apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
      version: "1.0"
  template:
    metadata:
      labels:
        app: kubia
        version: "1.0"
    spec:
      containers:
      - name: kubia
        image: luksa/kubia