apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-with-gitsync-pod
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: git
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  - image: openweb/git-sync
    name: git-sync
    env:
    - name: GIT_SYNC_REPO
      value: "https://github.com/joont92/kubia-website-example.git"
    - name: GIT_SYNC_DEST
      value: "/git"
    - name: GIT_SYNC_BRANCH
      value: "master"
    - name: GIT_SYNC_WAIT
      value: "10"
    volumeMounts:
    - name: git
      mountPath: /git
  volumes:
  - name: git
    emptyDir: {}